#version: '3.8'
#
#services:
#  db:
#    image: mariadb:10.11
#    container_name: booking-db
#    environment:
#      MYSQL_ROOT_PASSWORD: santoor711
#      MYSQL_DATABASE: booking
#      MYSQL_USER: ticket
#      MYSQL_PASSWORD: santoor711
#    ports:
#      - "3306"
#    volumes:
#      - db_data:/var/lib/mysql
#    restart: unless-stopped
#
#  app:
#    image: santoshkumar711/ticket-booking-app:v1
#    container_name: booking-app
#    depends_on:
#      - db
#    ports:
#      - "8000:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/booking
#      SPRING_DATASOURCE_USERNAME: ticket
#      SPRING_DATASOURCE_PASSWORD: santoor711
#    restart: always
#
#volumes:
#  db_data:
